# WITH TMP AS
# (
# SELECT COALESCE(LENGTH, "10") AS LENGTH
# FROM FISH_INFO
# )

# -- 코드를 작성해주세요
# SELECT ROUND(AVG(LENGTH),2) AS AVERAGE_LENGTH
# FROM TMP


SELECT ROUND(AVG(IFNULL(LENGTH, 10)),2) AS AVERAGE_LENGTH
FROM FISH_INFO