WITH B AS
(
    SELECT FOOD_TYPE, MAX(FAVORITES) AS TMP
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO AS A, B
WHERE A.FOOD_TYPE = B.FOOD_TYPE
AND A.FAVORITES = B.TMP
ORDER BY 1 DESC
