SELECT PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT*PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
INNER JOIN FOOD_ORDER AS O USING (PRODUCT_ID)
WHERE O.PRODUCE_DATE LIKE "2022-05%"
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY SUM(AMOUNT*PRICE) DESC, PRODUCT_ID ASC