SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS A
INNER JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = "DONE"
GROUP BY USER_ID
HAVING SUM(PRICE) >=700000
ORDER BY 3 ASC