WITH TMP AS
(
SELECT A.ITEM_ID AS TARGET_ID
FROM ITEM_TREE AS A
INNER JOIN ITEM_INFO AS B 
ON A.PARENT_ITEM_ID = B.ITEM_ID AND B.RARITY = "RARE"
)

SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO AS A, TMP AS B
WHERE B.TARGET_ID IS NOT NULL
AND A.ITEM_ID = B.TARGET_ID
ORDER BY 1 DESC
