# -- 코드를 입력하세요
# WITH TMP AS
# (
#     SELECT MCDP_CD, COUNT(APNT_NO) AS CNT
#     FROM APPOINTMENT
#     WHERE APNT_YMD LIKE "2022-05%"
#     GROUP BY MCDP_CD
# )

# SELECT A.MCDP_CD AS '진료과코드', TMP.CNT AS '5월예약건수'
# FROM APPOINTMENT AS A, TMP
# WHERE A.MCDP_CD = TMP.MCDP_CD

SELECT MCDP_CD, COUNT(APNT_NO) AS CNT
    FROM APPOINTMENT
    WHERE APNT_YMD LIKE "2022-05%"
    GROUP BY MCDP_CD
    ORDER BY CNT ASC, MCDP_CD ASC