WITH MAX_SIZE_TABLE AS
(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)


SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, B.MAX_SIZE-A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A
INNER JOIN MAX_SIZE_TABLE AS B 
ON YEAR(DIFFERENTIATION_DATE) = B.YEAR
ORDER BY 1, 2