WITH TMP AS
(
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
    
)

SELECT TMP.SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM HR_EMPLOYEES AS A
INNER JOIN TMP USING (EMP_NO)
ORDER BY SCORE DESC
LIMIT 1