WITH TMP AS
(
    SELECT DEPT_ID, AVG(SAL) AS SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
)

SELECT TMP.DEPT_ID, B.DEPT_NAME_EN, ROUND(TMP.SAL, 0) AS AVG_SAL
FROM TMP
INNER JOIN HR_DEPARTMENT AS B 
ON TMP.DEPT_ID = B.DEPT_ID
ORDER BY 3 DESC
