WITH TMP AS
(
SELECT BOOK_ID, CATEGORY, SALES, SALES_DATE
FROM BOOK_SALES AS A
INNER JOIN BOOK USING (BOOK_ID)
)

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES 
FROM TMP 
WHERE TMP.SALES_DATE LIKE "2022-01%"
GROUP BY CATEGORY
ORDER BY 1 
